baseurl = "http://mongodb.github.io"
MetaDataFormat = "yaml"

[indexes]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "1.4 Driver Docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "/1.4"
    weight = -115
[[menu.main]]
    name = "2.0 Driver Docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "/2.0"
    weight = -110
[[menu.main]]
    name = "1.1 Core Docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "/core"
    weight = -110
[[menu.main]]
    name = "Mongo DB Docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "http://mongodb.org"
    weight = -113
[[menu.main]]
    name = "/modules"
    pre = "<i class='fa fa-book'></i>"
    weight = -40