baseurl = "http://mongodb.github.io"
MetaDataFormat = "yaml"

[indexes]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "driver 1.4.X docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "1.4/"
    weight = -110
[[menu.main]]
    name = "driver 2.0.X docs"
    pre = "<i class='fa fa-file-text'></i>"
    url = "2.0/"
    weight = -105
[[menu.main]]
    name = "modules"
    pre = "<i class='fa fa-book'></i>"
    weight = -40